name: Auto-merge Dependabot PRs

on: [ pull_request_target ]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: major
          github-token: ${{ secrets.DEPENDABOT_AUTOMERGE_TOKEN }}
