name: On Push CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Grant rights
        run: chmod +x build.gradle.kts gradlew gradle

      - name: Build with Gradle
        id: build
        run: ./gradlew clean build
